name: 'Check SemVer'
description: 'Ensures incoming changes have a higher SemVer than master'
inputs: 
  master_version:
    description: "Master branch's SemVer"
    required: true
  pr_version:
    description: "PR's SemVer"
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
